data:
  train_path: '/Users/uralgimazov/Desktop/Python/Practice/Credit-Score-Prediction-Home-Credit-Bank/data/app_train_eda.csv'
  test_path: '/Users/uralgimazov/Desktop/Python/Practice/Credit-Score-Prediction-Home-Credit-Bank/data/application_test.csv'
  target_col: 'TARGET'
  drop_cols: ['SK_ID_CURR']
  test_size: 0.2
  # poly_degree: 3
  # poly_features_cols: ['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'AGE_YEARS']

model:
  name: 'LogisticRegression'
  params:
      verbose: -1
  search_space:
    C:
      type: int
      min: 1
      max: 10
train:
  cv_num: 2
  n_trials: 1
  save_model: false

general:
  seed: 42

