# Run from "Model Selection Workflow" with:
# python -m src.main configs/ex_config.yaml
data:
  train_path: '../../data/app_train_eda.csv'
  test_path: '../../data/application_test.csv'
  target_col: 'TARGET'
  drop_cols: ['SK_ID_CURR']
  test_size: 0.2

model:
  name: 'LogisticRegression'
  fixed_params: {}
  search_space:
    C:
      type: 'int'
      low: 1
      high: 1000

cv:
  metric: 'ROC_AUC'
  n_splits: 2
  n_trials: 3

seed: 42

tracker:
  exp_name: 'Tune'
  exp_dir: '../experiments'
  db_dir: '../db'
