[supervisord]
nodaemon=true

[program:backend]
command=uvicorn api.main:app --host 0.0.0.0 --port 8000
directory=/app
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autorestart=true
startretries=3
priority=10

[program:frontend]
command=streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
directory=/app
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autorestart=true
startretries=3
priority=20
